language: node_js
node_js:
  - "4"
  - "5"
  - "6"
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@latest; fi
  - sudo apt-get install libjpeg-dev libgif-dev
